#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SKILL_DIR = path.join(ROOT, "skills", "aivault");
const REFERENCES_DIR = path.join(SKILL_DIR, "references");
const CHECK = process.argv.includes("--check");

const GENERATED_NOTICE =
  "<!-- Generated by scripts/sync-skills.js. Edit docs/ sources, then run pnpm skills:sync. -->";

const referenceGroups = [
  {
    output: "getting-started.md",
    title: "Getting Started",
    sources: ["docs/getting-started.md", "docs/install.md", "docs/macos.md", "docs/linux-servers.md"],
  },
  {
    output: "cli-reference.md",
    title: "CLI Reference",
    sources: [
      "docs/cli/index.md",
      "docs/cli/vault-lifecycle.md",
      "docs/cli/secrets.md",
      "docs/cli/credentials.md",
      "docs/cli/providers.md",
      "docs/cli/capabilities.md",
      "docs/cli/invoke.md",
      "docs/cli/oauth.md",
    ],
  },
  {
    output: "provider-plugins.md",
    title: "Provider Plugins",
    sources: ["docs/providers/index.md", "docs/providers/postgres.md", "docs/cli/providers.md"],
  },
  {
    output: "registry-custom-providers.md",
    title: "Registry And Custom Providers",
    sources: [
      "docs/registry/index.md",
      "docs/registry/custom-providers.md",
      "docs/registry/schema.md",
      "docs/core/auth-strategies.md",
    ],
  },
  {
    output: "security-and-isolation.md",
    title: "Security And Isolation",
    sources: [
      "docs/core/security-model.md",
      "docs/core/scopes-and-isolation.md",
      "docs/security/threat-model.md",
      "docs/security/encryption.md",
      "docs/security/audit-log.md",
    ],
  },
  {
    output: "operations.md",
    title: "Operations",
    sources: ["docs/ops/daemon.md", "docs/ops/environment.md", "docs/ops/storage.md", "docs/ops/testing.md"],
  },
];

function readText(relativePath) {
  return fs.readFileSync(path.join(ROOT, relativePath), "utf8");
}

function stripFrontmatter(markdown) {
  if (!markdown.startsWith("---\n")) return markdown.trim();
  const end = markdown.indexOf("\n---", 4);
  if (end === -1) return markdown.trim();
  return markdown.slice(end + 4).trim();
}

function sourceHeading(relativePath) {
  const raw = readText(relativePath);
  const match = raw.match(/^title:\s*(.+)$/m);
  return match ? match[1].trim() : relativePath;
}

function renderSkill() {
  return `---
name: aivault
description: Complete guide for using aivault as a zero-trust local vault and proxy for API secrets. Use this skill when initializing or configuring aivault, managing secrets and credentials, invoking capability-backed API calls, setting workspace/group isolation, installing provider plugins such as Postgres, adding custom providers, or troubleshooting daemon and policy issues.
---

${GENERATED_NOTICE}

# aivault Runtime And Integration

This skill covers secure setup and day-to-day use of \`aivault\` for agent workflows. The detailed
reference files are generated from this repository's \`docs/\` sources; update docs first, then run
\`pnpm skills:sync\`.

## Quick Reference

| Resource | Path |
|----------|------|
| CLI binary | \`aivault\` |
| Daemon binary | \`aivaultd\` |
| Vault root (default) | \`~/.aivault/data/vault/\` |
| Daemon socket (default) | \`~/.aivault/run/aivaultd.sock\` |
| Repo docs source | \`docs/\` |
| Generated skill refs | \`skills/aivault/references/\` |

## Default Workflow

1. Check status and provider setup:
   - \`aivault status\`
   - \`aivault provider list -v\`
2. Store secrets in the vault, not in agent-readable env files:
   - \`aivault secrets create --name OPENAI_API_KEY --value "sk-..." --scope global\`
3. Inspect available capabilities:
   - \`aivault capability list\`
   - \`aivault capability describe openai/chat-completions\`
4. Invoke through the policy boundary:
   - \`aivault invoke openai/chat-completions --body '{"model":"gpt-5.2","messages":[{"role":"user","content":"hello"}]}'\`
5. Verify audit trail:
   - \`aivault audit\`

## Detailed References

Load only what is needed:

- [references/getting-started.md](references/getting-started.md) - installation, first-run setup, and secure invocation flow.
- [references/cli-reference.md](references/cli-reference.md) - command groups and practical command patterns.
- [references/provider-plugins.md](references/provider-plugins.md) - optional provider binaries, including Postgres setup and invocation.
- [references/registry-custom-providers.md](references/registry-custom-providers.md) - built-in registry model, schema, and custom provider flow.
- [references/security-and-isolation.md](references/security-and-isolation.md) - zero-trust properties, scope resolution, encryption, audit, and threat boundaries.
- [references/operations.md](references/operations.md) - daemon behavior, environment flags, storage layout, and testing commands.

## Essential Patterns

### Registry-backed secret provisioning

Use canonical secret names such as \`OPENAI_API_KEY\` so aivault can pin to a provider and
auto-enable capabilities.

### Capability-first invocation

Call \`aivault invoke <capability-id>\`, \`aivault json <capability-id>\`, or
\`aivault markdown <capability-id>\` instead of direct upstream calls with raw keys.

### Scoped tenancy controls

Use \`--scope workspace\` and \`--scope group\` for tenant isolation, then pass
\`--workspace-id\` and \`--group-id\` on invoke.

### Provider plugin activation

If a capability starts with a plugin namespace such as \`postgres/\`, check
\`aivault provider list -v\`, then install and enable the official provider before configuring
credentials:

\`\`\`bash
aivault provider install postgres --enable
\`\`\`

### Custom provider fallback

Only create manual credentials and capabilities when a provider is not in the built-in registry or
available as an official provider plugin.

## Common Mistakes To Avoid

1. Storing API keys in \`.env\` for untrusted agent code.
2. Invoking raw URLs instead of declared capabilities.
3. Forgetting scope context when debugging credential resolution.
4. Assuming caller-provided auth headers are allowed; the broker owns auth headers.
5. Treating custom providers as equally tamper-resistant as compiled registry providers.
6. Importing database client libraries or reading \`DATABASE_URL\` in agent-owned code when
   \`postgres/*\` capabilities are available.

## Maintenance

Run \`pnpm skills:sync\` after docs changes. Run \`pnpm skills:check\` in CI or before releases to
ensure \`skills/aivault\` still matches \`docs/\`.
`;
}

function renderReference(group) {
  const sourceList = group.sources.map((source) => `- \`${source}\``).join("\n");
  const sections = group.sources
    .map((source) => {
      const heading = sourceHeading(source);
      const body = stripFrontmatter(readText(source));
      return `## ${heading}\n\n_Source: \`${source}\`_\n\n${body}`;
    })
    .join("\n\n---\n\n");

  return `${GENERATED_NOTICE}
# ${group.title}

This reference is generated from:

${sourceList}

---

${sections}
`;
}

function plannedFiles() {
  const files = new Map();
  files.set(path.join(SKILL_DIR, "SKILL.md"), renderSkill());
  for (const group of referenceGroups) {
    files.set(path.join(REFERENCES_DIR, group.output), renderReference(group));
  }
  return files;
}

function ensureOnlyExpectedReferenceFiles(expectedFiles) {
  if (!fs.existsSync(REFERENCES_DIR)) return [];
  const expected = new Set(expectedFiles.keys());
  return fs
    .readdirSync(REFERENCES_DIR)
    .filter((name) => name.endsWith(".md"))
    .map((name) => path.join(REFERENCES_DIR, name))
    .filter((file) => !expected.has(file));
}

function main() {
  const files = plannedFiles();
  const staleFiles = ensureOnlyExpectedReferenceFiles(files);

  if (CHECK) {
    const drifted = [];
    for (const [file, content] of files) {
      if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content) {
        drifted.push(path.relative(ROOT, file));
      }
    }
    for (const file of staleFiles) drifted.push(path.relative(ROOT, file));
    if (drifted.length > 0) {
      console.error("Skill files are out of sync. Run `pnpm skills:sync`.");
      for (const file of drifted) console.error(`- ${file}`);
      process.exit(1);
    }
    console.log("Skill files are in sync.");
    return;
  }

  fs.mkdirSync(REFERENCES_DIR, { recursive: true });
  for (const [file, content] of files) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
  for (const file of staleFiles) fs.rmSync(file);
  console.log(`Synced ${files.size} skill files.`);
}

main();
